worker_processes 1;           #it is best to use "auto" on production instead of "1"

events {
    worker_connections 1024;    #the no of transaction the ngnix should take per time
}

http {
    server_tokens off;    #to hid the server details.
    include mime.types;

    upstream nodejs_cluster {
        least_conn;              #the algorithm to be used by nginx
        server localhost:3001;
        server localhost:3002;
        server localhost:3003;
    }

    server {
        listen 8080;
        server_name localhost;                  #on prod should be nimc.gov.ng

        location / {                            #where you are directing ngnix to pick from.
            proxy_pass http://nodejs_cluster;    #this is directing back to the upstream
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }
    }
}